version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_casamento
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: meu_casamento
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
    driver: local