# Generated by Django 5.0.6 on 2024-05-31 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listapresente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
