# Generated by Django 5.0.6 on 2024-05-31 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listapresente', '0002_alter_produto_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='descricao',
            field=models.TextField(default='exit'),
            preserve_default=False,
        ),
    ]
