# Generated by Django 5.0.6 on 2024-09-13 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convidados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acompanhante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='convidado',
            name='acompanhante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='convidados.acompanhante'),
            preserve_default=False,
        ),
    ]
