# Generated by Django 5.0.6 on 2024-09-13 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convidados', '0002_acompanhante_convidado_acompanhante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convidado',
            name='acompanhante',
        ),
        migrations.AddField(
            model_name='acompanhante',
            name='convidado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='convidados.convidado'),
            preserve_default=False,
        ),
    ]
