# Generated by Django 5.0.6 on 2024-09-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convidados', '0003_remove_convidado_acompanhante_acompanhante_convidado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convidado',
            name='codigo',
        ),
        migrations.AddField(
            model_name='convidado',
            name='presenca_confirmada',
            field=models.BooleanField(default=False),
        ),
    ]
