# Generated by Django 5.0.6 on 2024-09-15 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convidados', '0004_remove_convidado_codigo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConvidadoPresente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('presente', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_compra', models.DateField()),
            ],
        ),
    ]
